### ISSUE TITLE
Update font selection strategy tests and font resources.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2-tests#277] opened 2021-07-14 06:16 UTC
- [x] avoid use of default font in font selection strategy tests (non-portable behavior);
- [x] use _PT Mono_ then _Noto Sans_ (in this order);
- [x] use `&#x0300;`, COMBINING GRAVE, because it is missing from _PT Mono_ but included in _Noto Sans_;
- [x] update test description;
- [x] add font resources and update font specifications and license notices;
- [x] update expectations affected by above and by ttpe update, about which see https://github.com/skynav/ttt/pull/295;

**Comment by nigelmegitt** [comment] 2021-07-14 08:15
@skynavga please explain what the issue is that needs fixing - the changes committed cannot be reviewed without understanding what they are intended to achieve.

**Comment by skynavga** [comment] 2021-07-14 12:58
WIP; description TBD.

**Closed** 2021-08-08 13:19 UTC
